#In this notebook we're going to cover some of the most fundamental concepts of tensors using TensorFlow


#Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check the number of dimensions of a tensor 
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check the dimension of our vector
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check the dim of the matrix
matrix.ndim

2

In [8]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float32)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [9]:
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9], 
                      [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [10]:
tensor.ndim

3

### Creating tensor with tf.variable

In [11]:
v = tf.Variable(1.)
v.assign(2.)


<tf.Variable 'UnreadVariable' shape=() dtype=float32, numpy=2.0>

In [12]:
new_v = tf.Variable(1., shape=tf.TensorShape(None))
new_v.assign([[1.]])

<tf.Variable 'UnreadVariable' shape=<unknown> dtype=float32, numpy=array([[1.]], dtype=float32)>

In [13]:
# This creates a tensor that can be changed
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try to change something in the changeable tensor:
changeable_tensor[0].assign(7) 
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

# Creating random tensors


In [15]:
random_1 = tf.random.Generator.from_seed(42) 
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# What they will be
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

### Shuffle the order of elements in a tensor

In [16]:
# Shuffle a tensor 
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [1, 2]])
shuffled = tf.random.shuffle(not_shuffled)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 1,  2],
       [ 3,  4]], dtype=int32)>

In [17]:
rando = tf.random.uniform(shape=(4, 4), minval=100, maxval=105, seed=23)
rando2 = tf.random.Generator.from_seed(23)
rando2 = rando2.uniform(shape=(4, 4), minval=100, maxval=105)
rando, rando2, rando == rando2

(<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[103.798615, 101.09768 , 104.140114, 100.09026 ],
        [102.35404 , 100.33583 , 102.83132 , 103.0472  ],
        [103.970436, 100.96674 , 100.33444 , 103.246704],
        [104.06586 , 103.470955, 104.29224 , 102.31972 ]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[104.96255 , 101.02009 , 101.31995 , 103.97014 ],
        [103.59873 , 102.39229 , 101.0683  , 103.92064 ],
        [104.660355, 102.81289 , 102.37902 , 101.52718 ],
        [102.693924, 100.31878 , 103.17469 , 103.217865]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=bool, numpy=
 array([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])>)

In [18]:
rando3 = tf.random.uniform([3, 3], minval=1, maxval=2, seed=2)
tf.random.shuffle(rando3)


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1.4819697, 1.4783818, 1.5538954],
       [1.6787466, 1.7141509, 1.4698169],
       [1.2351481, 1.4386433, 1.4848769]], dtype=float32)>

In [19]:
tf.random.set_seed(44)

rando4 = tf.random.uniform(shape=(3, 3))
rando4

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.21691406, 0.7038727 , 0.28590095],
       [0.47886062, 0.97233224, 0.10853219],
       [0.14845335, 0.48970163, 0.20112908]], dtype=float32)>

In [20]:
# Seems like at the operational level it changes all the time, but not if we put a global seed
tf.random.set_seed(12345)
print(tf.random.uniform([2]))
print(tf.random.uniform([2]))

tf.Tensor([0.9594629  0.20031345], shape=(2,), dtype=float32)
tf.Tensor([0.8868036  0.42596483], shape=(2,), dtype=float32)


  ### Other ways to make tensors

In [21]:
#Create a tensor of all ones
tf.ones((10, 7))

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [22]:
# Create a tensor of all zeros
tf.zeros((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [23]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [24]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors
* Shape
* Rank
* Axis or dimension
* Size


In [25]:
print(tf.rank(A))
print(tf.shape(A), 'Can also just use A.shape', A.shape)
print(tf.size(A))
print(A.ndim)

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32) Can also just use A.shape (2, 3, 4)
tf.Tensor(24, shape=(), dtype=int32)
3


In [26]:
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [27]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [28]:
print('Datatype of every element:', rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Elements along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5


### Tensors can be indexed just like Python lists

In [29]:
# Get the first 2 elements of each dimension
print(rank_4_tensor[:2, :2, :2, :2])

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [30]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [31]:
tf.random.set_seed(3)
ten2 = tf.random.uniform(shape=(4, 3), minval=0, maxval=10, dtype=tf.int32)
ten2

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[4, 7, 4],
       [2, 9, 9],
       [1, 2, 4],
       [7, 7, 2]], dtype=int32)>

In [32]:
ten3 = ten2[..., tf.newaxis] # ... = every axis before this one in this case ten2[: ,:, tf.newaxis]
ten3

<tf.Tensor: shape=(4, 3, 1), dtype=int32, numpy=
array([[[4],
        [7],
        [4]],

       [[2],
        [9],
        [9]],

       [[1],
        [2],
        [4]],

       [[7],
        [7],
        [2]]], dtype=int32)>

In [33]:
# Alternative to tf.newaxis 
alt = tf.expand_dims(ten2, axis=0)
alt.ndim

3

In [34]:
# Just trying what else. Understand how to use it now.
ten_try = ten2[tf.newaxis, ...]
ten_try

<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
array([[[4, 7, 4],
        [2, 9, 9],
        [1, 2, 4],
        [7, 7, 2]]], dtype=int32)>

### Manipulating tensors (tensor operations)
`+`, `-`, `*`, `\`


In [35]:
ten3 + 10 # Easy to just add. Original not changed

<tf.Tensor: shape=(4, 3, 1), dtype=int32, numpy=
array([[[14],
        [17],
        [14]],

       [[12],
        [19],
        [19]],

       [[11],
        [12],
        [14]],

       [[17],
        [17],
        [12]]], dtype=int32)>

In [36]:
# We can use tensorflow built in function as well
tf.multiply(ten2, 10) # Faster to use

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[40, 70, 40],
       [20, 90, 90],
       [10, 20, 40],
       [70, 70, 20]], dtype=int32)>

# Matrix multiplication

In [37]:
tf.random.set_seed(4)
ten4 = tf.random.uniform(shape=(3, 4), minval=0, maxval=10, dtype=tf.int32)
tensor_mat = tf.matmul(ten2, ten4)
tensor_mat

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 63, 107,  86,  95],
       [ 86, 138, 118, 131],
       [ 37,  44,  41,  49],
       [ 70, 115,  89, 100]], dtype=int32)>

In [38]:
# Can just reshape into right dimension with tf.constant
tf.random.set_seed(18)
rx = tf.random.uniform(shape=(3,2), maxval=7, dtype=tf.int32)
qx = tf.random.uniform(shape=(3,2), maxval=10, dtype=tf.int32)
#qx = tf.constant(qx, shape=(2, 3))
#Can just use tf.reshape instead
#tf.reshape(qx, shape=(2, 3))

tf.matmul(rx, tf.reshape(qx, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14,  7, 22],
       [24, 12, 18],
       [28, 14, 26]], dtype=int32)>

### The dot product 
Matrix multiplication is also referred to as the dot product.
You can perform matrix muliplication using
* `tf.matmul()`
* `tf.tensordot()`

In [39]:
# Perform the dot product on rx and qx (requires transose)
tf.tensordot(tf.transpose(rx), qx, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 21],
       [32, 31]], dtype=int32)>

In [40]:
# Perform matrix multiplication between X and Y
tf.matmul(rx, tf.transpose(qx))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[11, 24, 12],
       [ 9, 28, 14],
       [13, 36, 18]], dtype=int32)>

In [41]:
tf.matmul(rx, tf.reshape(qx, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14,  7, 22],
       [24, 12, 18],
       [28, 14, 26]], dtype=int32)>

In [42]:
print('This is rx:', rx)
print('This is rx transposed:', tf.transpose(rx))
print('This is rx reshaped:', tf.reshape(rx, shape=(2, 3)))
print('This is qx:', qx)
print('This is qx transposed:', tf.transpose(qx))
print('This is qx reshaped:', tf.reshape(qx, shape=( 2, 3)))

This is rx: tf.Tensor(
[[5 1]
 [2 5]
 [4 5]], shape=(3, 2), dtype=int32)
This is rx transposed: tf.Tensor(
[[5 2 4]
 [1 5 5]], shape=(2, 3), dtype=int32)
This is rx reshaped: tf.Tensor(
[[5 1 2]
 [5 4 5]], shape=(2, 3), dtype=int32)
This is qx: tf.Tensor(
[[2 1]
 [4 4]
 [2 2]], shape=(3, 2), dtype=int32)
This is qx transposed: tf.Tensor(
[[2 4 2]
 [1 4 2]], shape=(2, 3), dtype=int32)
This is qx reshaped: tf.Tensor(
[[2 1 4]
 [4 2 2]], shape=(2, 3), dtype=int32)


### Changing the datatype of a tensor





In [43]:
# Create a new tensor with default datatype (float32)

fl = tf.constant([[3.3, 3.3],
                  [9.9, 9.9]])


In [44]:
# Change from float32 to flaot16
fl = tf.cast(fl, dtype=tf.float16)
fl


<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3.3, 3.3],
       [9.9, 9.9]], dtype=float16)>

### Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [45]:
 # getting the absolute values
 D = tf.constant([-7, -10])
 tf.abs(D)
 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* get the mean of a tensor
* Get the sum of a tensor

In [46]:
# Create a random tensor
E = tf.constant(np.random.randint(0, 100, size=50))
E


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([79,  9, 64, 19, 21, 59, 27, 59, 17, 74, 83, 94, 51, 10, 40, 67,  0,
       47, 31, 26, 28,  6, 96, 97,  4, 70,  8, 33, 32, 91, 83, 45, 83, 99,
       14, 66, 20, 47, 24, 32, 24, 91, 39, 21, 15, 14, 91, 24, 77, 73])>

In [47]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [48]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [49]:
# Find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=46>

In [50]:
# Find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2324>

In [51]:
E_mean = tf.reduce_mean(E)
E_diff = tf.subtract(E, E_mean)
E_new = tf.pow(E_diff, 2)
E_var = tf.reduce_sum(E_new) / 50

E_std = tf.sqrt(E_var)
E_var, E_std

(<tf.Tensor: shape=(), dtype=float64, numpy=911.36>,
 <tf.Tensor: shape=(), dtype=float64, numpy=30.18873962258113>)

### Find the positional maximum and minimum

In [52]:
# Finding the maximum
tf.reduce_max(E)
tf.argmax(E)
print(E[tf.argmax(E)])

tf.Tensor(99, shape=(), dtype=int64)


In [53]:
# Finding the minimum
tf.reduce_min(E)
tf.argmin(E)
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([79,  9, 64, 19, 21, 59, 27, 59, 17, 74, 83, 94, 51, 10, 40, 67,  0,
       47, 31, 26, 28,  6, 96, 97,  4, 70,  8, 33, 32, 91, 83, 45, 83, 99,
       14, 66, 20, 47, 24, 32, 24, 91, 39, 21, 15, 14, 91, 24, 77, 73])>

In [54]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50], maxval=10, dtype=tf.int32)
F

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([7, 9, 1, 6, 2, 4, 3, 3, 1, 1, 2, 0, 1, 1, 0, 8, 9, 2, 9, 9, 1, 2,
       7, 4, 9, 1, 1, 5, 6, 5, 0, 2, 1, 3, 8, 5, 3, 0, 3, 8, 2, 8, 1, 9,
       2, 4, 2, 9, 9, 6], dtype=int32)>

### Squeezing a tensor

In [55]:
# Freeballing here
tf.random.set_seed(3)
G = tf.constant(tf.random.uniform(shape=[50], maxval=5, dtype=tf.int32), shape=(1, 1, 1, 1, 50)) #Veldig nyttig å se alle dei forskjellige måtene å lage en tensor
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=int32, numpy=
array([[[[[4, 2, 4, 2, 4, 4, 1, 2, 4, 2, 2, 2, 2, 4, 0, 4, 1, 4, 2, 2,
           3, 2, 0, 0, 3, 0, 0, 2, 1, 2, 0, 0, 1, 2, 2, 1, 3, 2, 0, 3,
           0, 0, 4, 2, 4, 4, 3, 2, 3, 3]]]]], dtype=int32)>

In [56]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [57]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([4, 2, 4, 2, 4, 4, 1, 2, 4, 2, 2, 2, 2, 4, 0, 4, 1, 4, 2, 2, 3, 2,
       0, 0, 3, 0, 0, 2, 1, 2, 0, 0, 1, 2, 2, 1, 3, 2, 0, 3, 0, 0, 4, 2,
       4, 4, 3, 2, 3, 3], dtype=int32)>

In [58]:
# Try another one
tf.random.set_seed(4)
H = tf.random.uniform(shape=(30, 1, 1, 1), maxval=80, dtype=tf.int32)
H.shape

TensorShape([30, 1, 1, 1])

In [59]:
H_squeezed = tf.squeeze(H)
H_squeezed

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([67, 46, 35, 67, 51, 79, 26, 45, 57, 25, 66,  8, 58, 27, 54, 30, 25,
       62, 41, 50, 38, 16, 11, 10,  0,  4, 63, 36, 26, 70], dtype=int32)>

In [60]:
# Another one
tf.random.set_seed(5)
I = tf.random.uniform(shape=(1, 1, 10, 5), maxval=100, dtype=tf.int32)
I.shape

TensorShape([1, 1, 10, 5])

In [61]:
I_squeezed = tf.squeeze(I)
I_squeezed

<tf.Tensor: shape=(10, 5), dtype=int32, numpy=
array([[70, 71, 68, 66, 47],
       [96, 49,  5, 21, 11],
       [18, 95, 38,  7, 24],
       [59, 60, 70,  7, 71],
       [68,  1, 67, 95, 72],
       [37,  8, 61, 18, 50],
       [12, 49, 16, 17, 53],
       [22, 31, 45, 56, 56],
       [61, 72, 75, 79, 83],
       [29, 99, 21,  8, 95]], dtype=int32)>

### One-hot encoding tensors

In [62]:
# Numerical encode tensors (category to numbers)
some_list = [0, 1, 2, 3]

# One-hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>